chore: rdr2 referencess
aziontech/go-thoth pull request #8
Opened 2024-01-11 14:24 UTC by maxwelbm

https://reddead.fandom.com/pt-br/wiki/Gangue_Van_der_Linde

2024-01-11 14:26 UTC, PatrickMenoti submitted a review, later dismissed

2024-01-11 14:35 UTC, tiagokrebs requested changes
A little bit picky but maybe we should observe the [CONTRIBUTING](https://github.com/aziontech/go-thoth/blob/main/CONTRIBUTING.md) here, specially the rule 3.
> Respect: Please ensure that the names suggested are respectful and inclusive. Avoid any words that might be considered discriminatory, inappropriate, or disrespectful in any form.

Terms like "Crook", "Thief", "Harlot" could be considered disrespectful or carry negative connotations.  
Maybe there are more terms besides these that should not be used, look at [this conversation](https://chat.openai.com/share/7482d1c9-b0b5-4d30-b89e-c20a7fdee022) with ChatGPT about it.

2024-01-11 14:57 UTC, PatrickMenoti approved these changes, later dismissed

2024-01-11 17:19 UTC, tiagokrebs reviewed
Found some double nouns, also, what about this:
> Nouns: The nouns used for suggesting names should be simple, respectful, and related to technology or nerdy content. They should be a single word. Avoid using jargon or acronyms that might not be universally understood.

Some nouns do not have a single word, but many in cammel case, this is a new patterm, maybe we should follow the guideline, or change it.

2024-01-11 17:19 UTC, tiagokrebs commented on nouns.go
> +		"JavierEscuella",
Double noun here =D

2024-01-11 17:19 UTC, tiagokrebs commented on nouns.go
> +		"SimonPearson",
Double noun here too =D

2024-01-11 17:19 UTC, tiagokrebs commented on nouns.go
> +		"OrvilleSwanson",
Double noun here again =D

2024-01-11 17:19 UTC, tiagokrebs commented on nouns.go
> +		"BessieMatthews",
Last double noun =D

2024-02-03 17:19 UTC, tiagokrebs commented
@maxwelbm if you're not willing to pursue this change anymore we can close this pull request.

2024-02-04 13:23 UTC, maxwelbm commented
I'm going to add a test to check for duplicate adjectives or nouns, to avoid cases like this, I'll bring it up in a separate pr @tiagokrebs

2024-02-28 14:13 UTC, tiagokrebs approved these changes

2024-02-28 14:46 UTC, PatrickMenoti approved these changes

2024-02-28 14:47 UTC, merged